#define RESOURCE_PATH "/home/kaj/code/vvipers/res/"
#define VIPER_TEXTURE_FILE "viper_texture.png"
#define VIPER_MODEL_FILE "viper_model.json"
#define USER_CONFIGURATION_FILE "user.json"
#define VIPER_TEXTURE_FILE_PATH RESOURCE_PATH VIPER_TEXTURE_FILE
#define VIPER_MODEL_FILE_PATH RESOURCE_PATH VIPER_MODEL_FILE
#define USER_CONFIGURATION_FILE_PATH RESOURCE_PATH USER_CONFIGURATION_FILE
